# Generated by Django 5.1.6 on 2025-06-09 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_groups_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default='Default description', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(default='default,keywords', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='Default Title', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='general', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0-default, 1-Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default, 1-Trending'),
        ),
    ]
